### ISSUE TITLE
Openbox config

### ISSUE THREAD

**Issue by 0paIescent** [hrqmonteiro/openbox-dotfiles#1]
Thanks for all the configs! Really nice for someone who's just getting into learning Openbox. Would be willing to share your Openbox rc.xml maybe?

**Comment by hrqmonteiro** [comment]
You're welcome! I just uploaded the rc.xml, check the .config/openbox directory

You said you're just getting into Openbox, right? One tip: install obkey, its a graphical editor to rc.xml. when i started to mess with Openbox i used it and it really helped me :)

**Comment by 0paIescent** [comment]
Oh man that's awesome! I'll definitely check that out tomorrow, I've messed with obconf, but I didn't know about that. Thanks! :)
