### ISSUE TITLE
Transparent Tint2

### ISSUE THREAD

**Issue by Dentrax** [hrqmonteiro/openbox-dotfiles#2]
Hey,

I used it to try Tint 2 config. But it's completely transparent. How can I make it opaque like the screenshot given in the Readme file? Thank you...

![2018-08-15_00 29 31](https://user-images.githubusercontent.com/16493751/44119617-70756b02-a022-11e8-9744-c3d1ec25b6d0.png)

**Comment by hrqmonteiro** [comment]
It's my wallpaper. Since i use polybar over tint i configured both transparent and on my wallpaper i just created a white rectangle on it haha, to make it easier.

Here's the link for it if you want: https://raw.githubusercontent.com/hrqmonteiro/openbox-dotfiles/master/bg_dock_circle.png

**Comment by hrqmonteiro** [comment]
But if you want to make it white on tint just open tint config, go to my theme, go to Backgrounds and change the Panel Background to white.

**Comment by Dentrax** [comment]
I like your way. :+1: I already tried to configure it with tint2rc. But I was confused because there was 10 Background settings. Do I have to do all the background-color settings #ffffff which those in the background group?

**Comment by hrqmonteiro** [comment]
No, just the background called Panel and then only the first "Fill Color" to #FFF

Like this: 
![2018-08-17-174008_848x213_scrot](https://user-images.githubusercontent.com/17055027/44287837-a7b60580-a244-11e8-9646-76d49652f94d.png)

**Comment by hrqmonteiro** [comment]
If you are editing manual on tint2rc, it would be this: 
![2018-08-17-174229_403x237_scrot](https://user-images.githubusercontent.com/17055027/44287906-f19eeb80-a244-11e8-9831-128a8fca0903.png)

**Comment by Dentrax** [comment]
Thank you!

`background_color = #000000 100` worked for me.
